[package]
name = "nft_with_attr"
version = "0.0.1"

[addresses]
my_addr = "_"
std = "0x1"
aptos_framework = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/move-stdlib/", rev="aptos-cli-v1.0.0" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v1.0.0" }
# MoveStdlib = { local = "/Users/liaohua/aptos-core/aptos-move/framework/move-stdlib" }
# AptosFramework = { local = "/Users/liaohua/aptos-core/aptos-move/framework/aptos-framework" }

